# -*- coding: utf-8 -*-
# Import pygame's constants for identifying events, and add some of our own
from pygame.locals import *
SPEECH_RECOGNITION = USEREVENT+1
SPEECH_FALSERECOGNITION = SPEECH_RECOGNITION+1
SPEECH_SOUNDSTART = SPEECH_FALSERECOGNITION+1
SPEECH_SOUNDEND = SPEECH_SOUNDSTART+1
EYELINK_BUTTON_DOWN = SPEECH_SOUNDEND+1
EYELINK_BUTTON_UP = EYELINK_BUTTON_DOWN+1
CEDRUS_BUTTON_DOWN = EYELINK_BUTTON_UP+1
CEDRUS_BUTTON_UP = CEDRUS_BUTTON_DOWN + 1
